name: Variables and secrets
on: [push]

jobs:
  logs-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: "staging"
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR}}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR}}
      ENV_LEVEL_VAR: ${{vars.ENV_LEVEL_VAR}}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I Ran"
      - name: Log vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
